### ISSUE TITLE
Error: Template file does not exist

### ISSUE THREAD

**Issue by davidvasandani** [Zapotek/raw2vmdk#2]
running this command:

java -jar ~/Downloads/raw2vmdk-0.1.3.2-jar/raw2vmdk.jar /NetBoot/Masters/DEV/ChrisC-WIN_11.10.07_10.46.i386.disk0s3.dd ~/Desktop/chris.vmdk

gives me this error:

Analysing image:
/NetBoot/Masters/DEV/ChrisC-WIN_11.10.07_10.46.i386.disk0s3.dd [101811486720 bytes]

Number of sectors:  198850560
Number of cylinders:    0
Heads per track:    0
Sectors per track:  0

Loading VMDK template...

Error: Template file does not exist.

Any suggestions would be helpful. Thanks.

**Comment by Zapotek** [comment]
Hi, try running it from inside its own folder.
