### ISSUE TITLE
Minor bug when raw image is in drive's root - Windows 7 x64 v0.1.3.1

### ISSUE THREAD

**Issue by logan-jones** [Zapotek/raw2vmdk#3]
Creating a .vmdk that references a raw file on a drive's root in Win7 x64. Command issued is as follows:

java -jar raw2vmdk.jar R:\test.raw R:\test.vmdk

In R:\test.vmdk, the line that references the raw image reads:
RW 156301488 FLAT "R:9084_2012-09-05.raw"

when it should read:
RW 156301488 FLAT "R:\9084_2012-09-05.raw"

This leaves it unable to be mounted or loaded by any means until the backslash is inserted.

**Comment by Zapotek** [comment]
Haven't worked on this in years but I'll have a crack at it at the end of day.

**Comment by Zapotek** [comment]
Ah, I just remembered: https://github.com/Zapotek/raw2vmdk/blob/master/README#L44

Can't do much about that, it's how CLI args are handled it seems.
